language: python
python:
  - 3.6
cache:
  pip: true
  directories:
    - node_modules


# Use container-based infrastructure
dist: trusty
sudo: false

# Services
services:
  - postgresql

addons:
  postgresql: "9.6"

env:
  global:
    - DJANGO_SETTINGS_MODULE=mongodb_blog.settings.production
    - DATABASE_URL=postgres://postgres@localhost/test_db
    - SECRET_KEY=iamnotsosecret
    - ALLOWED_HOSTS=localhost

before_script:
  # Create a database
  - psql -c 'create database test_db;' -U postgres

# Package installation
install:
  # Install project dependencies
  - pip install -r requirements.txt

  # Install test dependencies
  - pip install flake8

  # Install node
  - nvm install 8

  # Move into the static_src folder where we will compile the FE
  - cd ./mongodb_blog/static_src

  # Install node dependencies
  -  npm install --quiet

  # Build the static files
  - npm run build:prod

  # Change back to the original folder
  - cd -


# Run the tests
script:
  # Run python code style checks
  - flake8 mongodb_blog

  # Run system checks
  - python manage.py check

  # Check for missing migrations
  - python manage.py makemigrations --check

  # Run tests
  - python manage.py test
