# For Dev only
FROM python:3.6.6-stretch

ENV PYTHONUNBUFFERED 1

RUN apt-get update && apt-get install postgresql-client -y

RUN mkdir /app
WORKDIR /app

# Install Python dependencies
ADD requirements.txt requirements.txt
RUN pip install -r requirements.txt

ADD . /app/
