# Generated by Django 2.0.8 on 2018-09-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customdocument',
            name='file_size',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
    ]
