# Generated by Django 2.0.3 on 2018-09-27 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('wagtailsearchpromotions', '0002_capitalizeverbose'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0040_page_draft_title'),
        ('news', '0002_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsindex',
            name='listing_image',
        ),
        migrations.RemoveField(
            model_name='newsindex',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='newsindex',
            name='social_image',
        ),
        migrations.RemoveField(
            model_name='newspage',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='newspage',
            name='listing_image',
        ),
        migrations.RemoveField(
            model_name='newspage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='newspage',
            name='social_image',
        ),
        migrations.RemoveField(
            model_name='newspagenewstype',
            name='news_type',
        ),
        migrations.RemoveField(
            model_name='newspagenewstype',
            name='page',
        ),
        migrations.RemoveField(
            model_name='newspagerelatedpage',
            name='page',
        ),
        migrations.RemoveField(
            model_name='newspagerelatedpage',
            name='source_page',
        ),
        migrations.DeleteModel(
            name='NewsType',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='NewsIndex',
        ),
        migrations.DeleteModel(
            name='NewsPage',
        ),
        migrations.DeleteModel(
            name='NewsPageNewsType',
        ),
        migrations.DeleteModel(
            name='NewsPageRelatedPage',
        ),
    ]
